version: '3'
services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app/shiryobukai-uni
    command: cargo watch -x fmt -s 'mold -run cargo run'
    ports:
      - "8080:80"
